<?php

declare(strict_types=1);

/**
 * Add Bluesky to the social link block configuration if not present.
 */
function ambientimpact_block_update_9201(): void {

  $config = \Drupal::service('config.factory')->getEditable(
    'ambientimpact_block.social_links',
  );

  if ($config->get('networks.bluesky') !== null) {
    return;
  }

  $networks = $config->get('networks');

  if (!is_array($networks)) {
    return;
  }

  $networks['bluesky'] = ['title' => 'Bluesky'];

  $config->set('networks', $networks)->save(true);

  // Delete the cached config so that Drupal starts using the new config. Note
  // that invalidating this cache ID doesn't seem to do it for whatever reason,
  // so we have to actually delete it.
  \Drupal::cache('config')->delete('ambientimpact_block.social_links');

}

/**
 * Rebuild block_view for social block attributes rework and new cache tags.
 */
function ambientimpact_block_update_9202(): void {

  // This is heavy handed as we want to avoid hard coding the theme that the
  // block is placed for, but there doesn't seem to be a more specific tag we
  // can use that doesn't require knowledge of the theme's name.
  //
  // This update adds the 'block_view:ambientimpact_block_social_links' tag that
  // should be invalidated in the future instead.
  \Drupal::service('cache_tags.invalidator')->invalidateTags(['block_view']);

}
